### ISSUE TITLE
Feature: a form of progress indication

### ISSUE THREAD

**Issue by silverdr** [cytopia/linux-timemachine#68]
I am unsure if it is feasible but some overview type of progress indication would be highly appreciated. `rsync`'s `--progress` option is not really usable for this purpose. Other than that - thanks for the tool!

**Comment by cytopia** [comment]
@silverdr thanks for the issue report.

This feature however will be out of scope for this project as I try to keep it as minimal as possible in order to retain maximum reliability (https://github.com/cytopia/linux-timemachine#lock-reliability). Less code is potentially less bugs, which is my highest priority for this project.

Only option is `--progress`, but might not really work for you as you've pointed out already.
