### ISSUE TITLE
Deleting old files

### ISSUE THREAD

**Issue by ghost** [cytopia/linux-timemachine#89]
Hi, I know you said:

"You can also safely delete the initial full backup directory without having to worry about losing any of your full backup data"

Does this mean I can delete *any* old backups by hand without breaking subsequent backups? Thanks :)

**Comment by bobafetthotmail** [comment]
I have been deleting old backups on Linux with no issues for a long time. 

The reason why you can do that is stated a line below the one you quoted
"rsync and [hardlinks](https://en.wikipedia.org/wiki/Hard_link) are magic :-)"

This tool uses rsync and a filesystem feature called hardlink, all modern filesystems support it, especially on Linux.

With hardlinking, files that don't change from one backup to the next are linked to the same data blocks at the filesystem level. The main benefit is saving a ton of space because you are not really storing a copy of the same files every time you run a backup.
Since hardlinks are a filesystem feature, they work at a lower level than files. There is no "original file" and "links to original file", but all hardlinked files are links to the same data. There is no hierarchy of first or last or "real file" and "links to the real file", they are all links so it does not matter.

**Comment by ghost** [comment]
Thanks Boba :) Yeah, I've been running this script every hour since early morning and deleted old backups and all seems fine. Yeah, I have a vague idea how this works, but I could never quite wrap my head around the concept of hard links. I know what they're supposed to do, but I'm quite fuzzy on the details, so to say :)

So this may just work for me. Lack of automated retention policy/logic shouldn't matter then if I can simply delete older backups by hand, do I have that right? 

Thanks again :)

**Comment by bobafetthotmail** [comment]
yeah a while ago I have evaluated some form of automated retention/deletion program but since most of my data does not change or grow very fast anyway I've been simply deleting old backups manually when I see the backup USB drives are getting too full

**Comment by ghost** [comment]
The thing is that I'm coming from Windows where I use Retrospect for backups and I have not found a proper backup app on Linux that does "searchable backups".  I like to be able to search my backups for files. 

Using a script like gives me that option as the backups are just files that I can search for using my file manager. 

There is another script like this, that mimics the TimeMachine behavior, here on Github, that has a retention logic built in, but it has a flaw that I am unable to deal with: it backs up everything every time it runs if the source is on BTRFS, pretty much making the script useless. I'm on Fedora 41 now and BTRFS is the default FS.

In the end, retention logic doesn't really matter if I can simply delete the old backups.

**Comment by ghost** [comment]
I'm closing this. I've ran this script for two weeks, every hour, deleting old backups without any issues. Thank you!
